# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJnrNjmdhsz7eWQCsDdWNLjJ_1EONPM1
"""

import pandas as pd
import numpy as np
import logging
import os

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

from google.colab import drive
drive.mount('/content/drive')

INPUT_PATH  = '/content/drive/MyDrive/26 Spring Sem/DS4320/Project 1/raw data/diabetic_data.csv'
OUTPUT_DIR  = '/content/drive/MyDrive/26 Spring Sem/DS4320/Project 1/'

df = pd.read_csv(INPUT_PATH)
logger.info(f'Loaded diabetic_data.csv — {df.shape[0]:,} rows × {df.shape[1]} columns')

#identifing the section of columns that is just medicines
all_cols  = list(df.columns)
start_col = 'metformin'
end_col   = 'metformin-pioglitazone'

start_idx = all_cols.index(start_col)
end_idx   = all_cols.index(end_col)
med_cols  = all_cols[start_idx : end_idx + 1]   # 23 columns

logger.info(f'Medicine columns ({len(med_cols)}): {start_col} → {end_col}')

# medicines.csv — encounter_id + all 23 medicine columns
medicines_df = df[['encounter_id'] + med_cols].copy()

# diabetic_data.csv — everything except the medicine columns
# encounter_id is NOT in med_cols so it stays automatically
remaining_cols = [c for c in all_cols if c not in med_cols]
diabetic_df    = df[remaining_cols].copy()

#saving the new csv files (to my actual google drive this time)
os.makedirs(OUTPUT_DIR, exist_ok=True)

medicines_df.to_csv(os.path.join(OUTPUT_DIR, 'medicines.csv'),     index=False)
diabetic_df.to_csv( os.path.join(OUTPUT_DIR, 'diabetic_data.csv'),  index=False)

logger.info(f'medicines.csv     — {medicines_df.shape[0]:,} rows × {medicines_df.shape[1]} cols')
logger.info(f'diabetic_data.csv — {diabetic_df.shape[0]:,} rows × {diabetic_df.shape[1]} cols')

# Confirm encounter_id is present in both files
if 'encounter_id' in diabetic_df.columns:
    print('encounter_id present in diabetic_data')
else:
    print('encounter_id missing from diabetic_data')

if 'encounter_id' in medicines_df.columns:
    print('encounter_id present in medicines')
else:
    print('encounter_id missing from medicines')

# Confirm no medicine columns leaked into diabetic_data
leaked_cols = []
for c in med_cols:
    if c in diabetic_df.columns:
        leaked_cols.append(c)

if leaked_cols:
    print(f'Warning: {leaked_cols} leaked into diabetic_data.csv')
else:
    print('No medicine columns leaked into diabetic_data.')

logger.info('Validation process completed.')

def clean_diabetic_data(df):
    logger.info("Starting data cleaning process...")

    # 1. Drop columns with >50% missing values
    initial_cols_to_drop = ['weight', 'payer_code', 'medical_specialty']

    cols_to_drop = [col for col in initial_cols_to_drop if col in df.columns]

    # 2. Add indicator feature `weight_missing` if `weight` column was dropped
    if 'weight' in cols_to_drop:
        # First, ensure '?' are replaced with NaN to correctly identify missingness for 'weight'
        df_temp = df.replace('?', np.nan).copy()
        df['weight_missing'] = df_temp['weight'].isna().astype(int)
        logger.info("Added 'weight_missing' indicator feature.")

    df = df.drop(columns=cols_to_drop)
    logger.info(f"Dropped columns: {cols_to_drop}")

    # 3. Replace '?' with NaN
    df = df.replace('?', np.nan)
    logger.info("Replaced '?' with NaN.")

    # 4. Binarize the target variable (`readmitted_30d`)
    df['readmitted_30d'] = (df['readmitted'] == '<30').astype(int)
    df = df.drop(columns=['readmitted'])
    logger.info("Binarized 'readmitted' to 'readmitted_30d'.")

    # 5. Encode categorical features
    categorical_cols = df.select_dtypes(include='object').columns
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
    logger.info(f"One-hot encoded categorical features: {list(categorical_cols)}")

    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = pd.to_numeric(df[col], errors='coerce')

    df = df.fillna(0)
    logger.info("Filled NaN values with 0 after one-hot encoding.")

    final_cols_to_keep = [
        'encounter_id', 'patient_nbr', 'admission_type_id', 'discharge_disposition_id',
        'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures',
        'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient',
        'number_diagnoses', 'weight_missing', 'readmitted_30d'
    ]

    # Add all one-hot encoded columns derived from the explicitly requested base categorical features
    # Interpreting 'diag_X_group' as 'diag_X' for OHE base name
    ohe_base_features = [
        'race', 'gender', 'A1Cresult', 'insulin', 'change', 'diabetesMed',
        'diag_1', 'diag_2', 'diag_3' # Based on interpretation of diag_X_group
    ]

    for base_feature in ohe_base_features:
        # Find all columns that start with the base feature name (e.g., 'race_')
        dummy_cols = [col for col in df.columns if col.startswith(f'{base_feature}_')]
        final_cols_to_keep.extend(dummy_cols)

    # Filter df to only include these columns, handling potential missing columns
    # due to specific dummy variable instances not being present in the dataset.
    df = df[[col for col in final_cols_to_keep if col in df.columns]]
    logger.info(f"Filtered DataFrame to keep only requested columns. Final shape: {df.shape}")

    logger.info("Data cleaning process completed.")
    return df

# --- Apply the cleaning function and save the data ---

# Ensure og_df is loaded (as per previous cells)
INPUT_PATH_CLEANING  = '/content/drive/MyDrive/26 Spring Sem/DS4320/Project 1/diabetic_data.csv'
og_df = pd.read_csv(INPUT_PATH_CLEANING)
logger.info(f"Loaded original diabetic data from '{INPUT_PATH_CLEANING}' for cleaning.")

cleaned_df = clean_diabetic_data(og_df.copy()) # Use a copy to avoid modifying the original og_df

# Save the cleaned DataFrame
OUTPUT_PATH_CLEANED = '/content/drive/MyDrive/26 Spring Sem/DS4320/Project 1/diabetic_readmission_cleaned.csv'
cleaned_df.to_csv(OUTPUT_PATH_CLEANED, index=False)
logger.info(f"Cleaned data saved to '{OUTPUT_PATH_CLEANED}'")

logger.info(f"Cleaned DataFrame shape: {cleaned_df.shape}")
logger.info("Cleaned DataFrame head:\n" + str(cleaned_df.head()))