# -*- coding: utf-8 -*-
"""id_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwmSfagqX7ydzYTgfQpq7VQzHZ4q3qOk
"""

import pandas as pd
import logging
import os

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

from google.colab import drive
drive.mount('/content/drive')

# Load IDs_mapping.csv — the raw companion file from the UCI download
ids = pd.read_csv('/content/drive/MyDrive/26 Spring Sem/DS4320/Project 1/raw data/IDS_mapping.csv')
print(ids.head(10))
print(ids['admission_type_id'].unique())

# The file uses NaN rows to separate the three sections, so going to use that as the boundry for the three new tables
boundary = ids['admission_type_id'].isna()
group_id = boundary.cumsum()

# Drop the NaN separator rows, then split by group
clean = ids[~boundary].copy()

admission_type        = clean[group_id[~boundary] == 0].reset_index(drop=True)
discharge_disposition = clean[group_id[~boundary] == 1].reset_index(drop=True)
admission_source      = clean[group_id[~boundary] == 2].reset_index(drop=True)

admission_type = admission_type.rename(
    columns={'admission_type_id': 'admission_type_id', 'description': 'description'}
)
discharge_disposition = discharge_disposition.rename(
    columns={'admission_type_id': 'discharge_disposition_id'}
)
admission_source = admission_source.rename(
    columns={'admission_type_id': 'admission_source_id'}
)

output_dir = 'data/'
os.makedirs(output_dir, exist_ok=True)

tables = {
    'admission_type_id':        admission_type,
    'discharge_disposition_id':  discharge_disposition,
    'admission_source_id':       admission_source,
}

for name, df in tables.items():
    path = os.path.join(output_dir, f'{name}.csv')
    df.to_csv(path, index=False)
    logger.info(f'Saved {name}.csv — {len(df)} rows → {path}')

for name, df in tables.items():
    print(f'\n=== {name} ({len(df)} rows) ===')
    print(df.to_string(index=False))